#spring.h2.console.enabled=true
#spring.datasource.platform=h2
#spring.datasource.url=jdbc:h2:mem:Customer
#server.port = 8080

server:
  port:  8080

spring:
  h2:
    console:  
      enabled:  true
            
  datasource:   
    url:  jdbc:h2:mem:Customer


#spring.datasource.url=jdbc:postgresql://localhost:5432/Jeevitha
#spring.jpa.properties.hibernate.default_schema = public
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true